name: Build MyOS

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      options: --privileged

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Fix APT sources (Debian Bookworm ONLY)
        run: |
          rm -f /etc/apt/sources.list
          rm -f /etc/apt/sources.list.d/*

          cat <<EOF > /etc/apt/sources.list
          deb http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
          deb http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware
          deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
          EOF

      - name: Update system
        run: |
          apt-get clean
          apt-get update -y

      - name: Install build dependencies
        run: |
          apt-get install -y \
            build-essential \
            grub-pc-bin \
            grub-efi-amd64-bin \
            xorriso \
            squashfs-tools \
            debootstrap \
            curl \
            wget \
            git

      - name: Build OS
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myos-build
          path: |
            *.iso
