name: Build Debian Linux ISO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          live-build \
          debootstrap \
          debian-archive-keyring \
          squashfs-tools \
          xorriso \
          ca-certificates

    - name: Configure live-build
      run: |
        cd live-build
        sudo lb config \
          --distribution bookworm \
          --binary-images iso-hybrid \
          --archive-areas "main contrib non-free non-free-firmware" \
          --mirror-bootstrap https://deb.debian.org/debian/ \
          --mirror-binary https://deb.debian.org/debian/ \
          --mirror-chroot https://deb.debian.org/debian/ \
          --mirror-security https://security.debian.org/ \
          --security true


    - name: Build ISO
      run: |
        cd live-build
        sudo lb build

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: YourOS-ISO
        path: live-build/*.iso
